// Mock data for 2023/24 EPL season

export const mockMatches = [
  // Gameweek 1 - August 2023
  { id: 1, matchday: 1, utcDate: "2023-08-11T19:00:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Nottingham Forest FC", shortName: "Nottm Forest", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 351, name: "Arsenal FC", shortName: "Arsenal", crest: "https://crests.football-data.org/57.png" }, score: { fullTime: { home: 1, away: 2 } } },
  { id: 2, matchday: 1, utcDate: "2023-08-12T12:30:00Z", status: "FINISHED", homeTeam: { id: 402, name: "Burnley FC", shortName: "Burnley", crest: "https://crests.football-data.org/328.png" }, awayTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, score: { fullTime: { home: 0, away: 3 } } },
  { id: 3, matchday: 1, utcDate: "2023-08-12T15:00:00Z", status: "FINISHED", homeTeam: { id: 58, name: "Aston Villa FC", shortName: "Aston Villa", crest: "https://crests.football-data.org/58.png" }, awayTeam: { id: 354, name: "Newcastle United FC", shortName: "Newcastle", crest: "https://crests.football-data.org/67.png" }, score: { fullTime: { home: 5, away: 1 } } },
  { id: 4, matchday: 1, utcDate: "2023-08-12T15:00:00Z", status: "FINISHED", homeTeam: { id: 71, name: "Crystal Palace FC", shortName: "Crystal Palace", crest: "https://crests.football-data.org/354.png" }, awayTeam: { id: 60, name: "Sheffield United FC", shortName: "Sheffield Utd", crest: "https://crests.football-data.org/356.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 5, matchday: 1, utcDate: "2023-08-12T15:00:00Z", status: "FINISHED", homeTeam: { id: 67, name: "Everton FC", shortName: "Everton", crest: "https://crests.football-data.org/62.png" }, awayTeam: { id: 76, name: "Fulham FC", shortName: "Fulham", crest: "https://crests.football-data.org/63.png" }, score: { fullTime: { home: 0, away: 1 } } },
  { id: 6, matchday: 1, utcDate: "2023-08-12T15:00:00Z", status: "FINISHED", homeTeam: { id: 397, name: "Luton Town FC", shortName: "Luton", crest: "https://crests.football-data.org/1031.png" }, awayTeam: { id: 328, name: "Brighton & Hove Albion FC", shortName: "Brighton", crest: "https://crests.football-data.org/397.png" }, score: { fullTime: { home: 2, away: 4 } } },
  { id: 7, matchday: 1, utcDate: "2023-08-12T17:30:00Z", status: "FINISHED", homeTeam: { id: 63, name: "Brentford FC", shortName: "Brentford", crest: "https://crests.football-data.org/402.png" }, awayTeam: { id: 351, name: "Tottenham Hotspur FC", shortName: "Tottenham", crest: "https://crests.football-data.org/73.png" }, score: { fullTime: { home: 2, away: 2 } } },
  { id: 8, matchday: 1, utcDate: "2023-08-13T14:00:00Z", status: "FINISHED", homeTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, awayTeam: { id: 61, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png" }, score: { fullTime: { home: 1, away: 1 } } },
  { id: 9, matchday: 1, utcDate: "2023-08-13T16:30:00Z", status: "FINISHED", homeTeam: { id: 73, name: "Wolverhampton Wanderers FC", shortName: "Wolves", crest: "https://crests.football-data.org/76.png" }, awayTeam: { id: 563, name: "West Ham United FC", shortName: "West Ham", crest: "https://crests.football-data.org/563.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 10, matchday: 1, utcDate: "2023-08-14T19:00:00Z", status: "FINISHED", homeTeam: { id: 74, name: "Manchester United FC", shortName: "Man United", crest: "https://crests.football-data.org/66.png" }, awayTeam: { id: 1044, name: "AFC Bournemouth", shortName: "Bournemouth", crest: "https://crests.football-data.org/1044.png" }, score: { fullTime: { home: 1, away: 0 } } },

  // Gameweek 2 - August 2023
  { id: 11, matchday: 2, utcDate: "2023-08-19T12:30:00Z", status: "FINISHED", homeTeam: { id: 57, name: "Arsenal FC", shortName: "Arsenal", crest: "https://crests.football-data.org/57.png" }, awayTeam: { id: 63, name: "Crystal Palace FC", shortName: "Crystal Palace", crest: "https://crests.football-data.org/354.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 12, matchday: 2, utcDate: "2023-08-19T15:00:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 58, name: "Newcastle United FC", shortName: "Newcastle", crest: "https://crests.football-data.org/67.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 13, matchday: 2, utcDate: "2023-08-19T15:00:00Z", status: "FINISHED", homeTeam: { id: 67, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png" }, awayTeam: { id: 402, name: "Luton Town FC", shortName: "Luton", crest: "https://crests.football-data.org/1031.png" }, score: { fullTime: { home: 3, away: 0 } } },
  { id: 14, matchday: 2, utcDate: "2023-08-19T15:00:00Z", status: "FINISHED", homeTeam: { id: 328, name: "Brighton & Hove Albion FC", shortName: "Brighton", crest: "https://crests.football-data.org/397.png" }, awayTeam: { id: 73, name: "West Ham United FC", shortName: "West Ham", crest: "https://crests.football-data.org/563.png" }, score: { fullTime: { home: 4, away: 2 } } },
  { id: 15, matchday: 2, utcDate: "2023-08-19T17:30:00Z", status: "FINISHED", homeTeam: { id: 66, name: "Tottenham Hotspur FC", shortName: "Tottenham", crest: "https://crests.football-data.org/73.png" }, awayTeam: { id: 74, name: "Manchester United FC", shortName: "Man United", crest: "https://crests.football-data.org/66.png" }, score: { fullTime: { home: 2, away: 0 } } },
  { id: 16, matchday: 2, utcDate: "2023-08-20T14:00:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Nottingham Forest FC", shortName: "Nottm Forest", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 66, name: "Sheffield United FC", shortName: "Sheffield Utd", crest: "https://crests.football-data.org/356.png" }, score: { fullTime: { home: 2, away: 1 } } },
  { id: 17, matchday: 2, utcDate: "2023-08-20T14:00:00Z", status: "FINISHED", homeTeam: { id: 76, name: "Fulham FC", shortName: "Fulham", crest: "https://crests.football-data.org/63.png" }, awayTeam: { id: 58, name: "Brentford FC", shortName: "Brentford", crest: "https://crests.football-data.org/402.png" }, score: { fullTime: { home: 0, away: 3 } } },
  { id: 18, matchday: 2, utcDate: "2023-08-20T14:00:00Z", status: "FINISHED", homeTeam: { id: 563, name: "West Ham United FC", shortName: "West Ham", crest: "https://crests.football-data.org/563.png" }, awayTeam: { id: 67, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png" }, score: { fullTime: { home: 3, away: 1 } } },
  { id: 19, matchday: 2, utcDate: "2023-08-20T16:30:00Z", status: "FINISHED", homeTeam: { id: 1044, name: "AFC Bournemouth", shortName: "Bournemouth", crest: "https://crests.football-data.org/1044.png" }, awayTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, score: { fullTime: { home: 1, away: 3 } } },
  { id: 20, matchday: 2, utcDate: "2023-08-21T19:00:00Z", status: "FINISHED", homeTeam: { id: 60, name: "Aston Villa FC", shortName: "Aston Villa", crest: "https://crests.football-data.org/58.png" }, awayTeam: { id: 67, name: "Everton FC", shortName: "Everton", crest: "https://crests.football-data.org/62.png" }, score: { fullTime: { home: 4, away: 0 } } },

  // Gameweek 3
  { id: 21, matchday: 3, utcDate: "2023-08-26T12:30:00Z", status: "FINISHED", homeTeam: { id: 57, name: "Arsenal FC", shortName: "Arsenal", crest: "https://crests.football-data.org/57.png" }, awayTeam: { id: 74, name: "Manchester United FC", shortName: "Man United", crest: "https://crests.football-data.org/66.png" }, score: { fullTime: { home: 3, away: 1 } } },
  { id: 22, matchday: 3, utcDate: "2023-08-26T15:00:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 76, name: "Fulham FC", shortName: "Fulham", crest: "https://crests.football-data.org/63.png" }, score: { fullTime: { home: 5, away: 1 } } },
  { id: 23, matchday: 3, utcDate: "2023-08-26T15:00:00Z", status: "FINISHED", homeTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, awayTeam: { id: 328, name: "Aston Villa FC", shortName: "Aston Villa", crest: "https://crests.football-data.org/58.png" }, score: { fullTime: { home: 3, away: 0 } } },
  { id: 24, matchday: 3, utcDate: "2023-08-26T15:00:00Z", status: "FINISHED", homeTeam: { id: 60, name: "Sheffield United FC", shortName: "Sheffield Utd", crest: "https://crests.football-data.org/356.png" }, awayTeam: { id: 67, name: "Nottingham Forest FC", shortName: "Nottm Forest", crest: "https://crests.football-data.org/65.png" }, score: { fullTime: { home: 0, away: 2 } } },
  { id: 25, matchday: 3, utcDate: "2023-08-27T14:00:00Z", status: "FINISHED", homeTeam: { id: 354, name: "Newcastle United FC", shortName: "Newcastle", crest: "https://crests.football-data.org/67.png" }, awayTeam: { id: 1044, name: "AFC Bournemouth", shortName: "Bournemouth", crest: "https://crests.football-data.org/1044.png" }, score: { fullTime: { home: 1, away: 1 } } },
  { id: 26, matchday: 3, utcDate: "2023-08-27T14:00:00Z", status: "FINISHED", homeTeam: { id: 63, name: "Brentford FC", shortName: "Brentford", crest: "https://crests.football-data.org/402.png" }, awayTeam: { id: 67, name: "Everton FC", shortName: "Everton", crest: "https://crests.football-data.org/62.png" }, score: { fullTime: { home: 3, away: 1 } } },
  { id: 27, matchday: 3, utcDate: "2023-08-27T14:00:00Z", status: "FINISHED", homeTeam: { id: 354, name: "Crystal Palace FC", shortName: "Crystal Palace", crest: "https://crests.football-data.org/354.png" }, awayTeam: { id: 76, name: "Wolves", shortName: "Wolves", crest: "https://crests.football-data.org/76.png" }, score: { fullTime: { home: 3, away: 2 } } },
  { id: 28, matchday: 3, utcDate: "2023-08-27T16:30:00Z", status: "FINISHED", homeTeam: { id: 61, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png" }, awayTeam: { id: 397, name: "Luton Town FC", shortName: "Luton", crest: "https://crests.football-data.org/1031.png" }, score: { fullTime: { home: 3, away: 0 } } },
  { id: 29, matchday: 3, utcDate: "2023-08-28T19:00:00Z", status: "FINISHED", homeTeam: { id: 73, name: "Tottenham Hotspur FC", shortName: "Tottenham", crest: "https://crests.football-data.org/73.png" }, awayTeam: { id: 328, name: "Brighton & Hove Albion FC", shortName: "Brighton", crest: "https://crests.football-data.org/397.png" }, score: { fullTime: { home: 2, away: 2 } } },
  { id: 30, matchday: 3, utcDate: "2023-08-28T19:00:00Z", status: "FINISHED", homeTeam: { id: 402, name: "Burnley FC", shortName: "Burnley", crest: "https://crests.football-data.org/328.png" }, awayTeam: { id: 563, name: "West Ham United FC", shortName: "West Ham", crest: "https://crests.football-data.org/563.png" }, score: { fullTime: { home: 1, away: 3 } } },

  // Some later matches for variety
  { id: 31, matchday: 4, utcDate: "2023-09-02T12:30:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 354, name: "Fulham FC", shortName: "Fulham", crest: "https://crests.football-data.org/63.png" }, score: { fullTime: { home: 5, away: 1 } } },
  { id: 32, matchday: 4, utcDate: "2023-09-02T15:00:00Z", status: "FINISHED", homeTeam: { id: 57, name: "Arsenal FC", shortName: "Arsenal", crest: "https://crests.football-data.org/57.png" }, awayTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, score: { fullTime: { home: 2, away: 2 } } },
  { id: 33, matchday: 4, utcDate: "2023-09-03T14:00:00Z", status: "FINISHED", homeTeam: { id: 58, name: "Aston Villa FC", shortName: "Aston Villa", crest: "https://crests.football-data.org/58.png" }, awayTeam: { id: 61, name: "Chelsea FC", shortName: "Chelsea", crest: "https://crests.football-data.org/61.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 34, matchday: 4, utcDate: "2023-09-03T14:00:00Z", status: "FINISHED", homeTeam: { id: 73, name: "Tottenham Hotspur FC", shortName: "Tottenham", crest: "https://crests.football-data.org/73.png" }, awayTeam: { id: 74, name: "Manchester United FC", shortName: "Man United", crest: "https://crests.football-data.org/66.png" }, score: { fullTime: { home: 2, away: 0 } } },
  { id: 35, matchday: 5, utcDate: "2023-09-16T12:30:00Z", status: "FINISHED", homeTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, awayTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 36, matchday: 5, utcDate: "2023-09-16T15:00:00Z", status: "FINISHED", homeTeam: { id: 354, name: "Newcastle United FC", shortName: "Newcastle", crest: "https://crests.football-data.org/67.png" }, awayTeam: { id: 57, name: "Arsenal FC", shortName: "Arsenal", crest: "https://crests.football-data.org/57.png" }, score: { fullTime: { home: 0, away: 1 } } },
  { id: 37, matchday: 5, utcDate: "2023-09-17T14:00:00Z", status: "FINISHED", homeTeam: { id: 563, name: "West Ham United FC", shortName: "West Ham", crest: "https://crests.football-data.org/563.png" }, awayTeam: { id: 58, name: "Aston Villa FC", shortName: "Aston Villa", crest: "https://crests.football-data.org/58.png" }, score: { fullTime: { home: 1, away: 2 } } },
  { id: 38, matchday: 6, utcDate: "2023-09-23T12:30:00Z", status: "FINISHED", homeTeam: { id: 65, name: "Manchester City FC", shortName: "Man City", crest: "https://crests.football-data.org/65.png" }, awayTeam: { id: 354, name: "Newcastle United FC", shortName: "Newcastle", crest: "https://crests.football-data.org/67.png" }, score: { fullTime: { home: 3, away: 3 } } },
  { id: 39, matchday: 6, utcDate: "2023-09-24T14:00:00Z", status: "FINISHED", homeTeam: { id: 74, name: "Manchester United FC", shortName: "Man United", crest: "https://crests.football-data.org/66.png" }, awayTeam: { id: 402, name: "Burnley FC", shortName: "Burnley", crest: "https://crests.football-data.org/328.png" }, score: { fullTime: { home: 1, away: 0 } } },
  { id: 40, matchday: 6, utcDate: "2023-09-24T16:30:00Z", status: "FINISHED", homeTeam: { id: 328, name: "Brighton & Hove Albion FC", shortName: "Brighton", crest: "https://crests.football-data.org/397.png" }, awayTeam: { id: 64, name: "Liverpool FC", shortName: "Liverpool", crest: "https://crests.football-data.org/64.png" }, score: { fullTime: { home: 2, away: 2 } } },
];

// Official 2023/24 final standings (football-data.org format)
export const mockStandings = {
  standings: [
    {
      table: [
        { position: 1,  team: { id: 65, name: "Manchester City FC",             shortName: "Man City",       crest: "https://crests.football-data.org/65.png"   }, playedGames: 38, won: 28, draw: 7,  lost: 3,  points: 91, goalsFor: 96, goalsAgainst: 45, goalDifference: 51 },
        { position: 2,  team: { id: 57, name: "Arsenal FC",                     shortName: "Arsenal",        crest: "https://crests.football-data.org/57.png"   }, playedGames: 38, won: 28, draw: 5,  lost: 5,  points: 89, goalsFor: 91, goalsAgainst: 29, goalDifference: 62 },
        { position: 3,  team: { id: 64, name: "Liverpool FC",                   shortName: "Liverpool",      crest: "https://crests.football-data.org/64.png"   }, playedGames: 38, won: 24, draw: 10, lost: 4,  points: 82, goalsFor: 86, goalsAgainst: 41, goalDifference: 45 },
        { position: 4,  team: { id: 58, name: "Aston Villa FC",                 shortName: "Aston Villa",    crest: "https://crests.football-data.org/58.png"   }, playedGames: 38, won: 20, draw: 8,  lost: 10, points: 68, goalsFor: 76, goalsAgainst: 61, goalDifference: 15 },
        { position: 5,  team: { id: 73, name: "Tottenham Hotspur FC",           shortName: "Tottenham",      crest: "https://crests.football-data.org/73.png"   }, playedGames: 38, won: 20, draw: 6,  lost: 12, points: 66, goalsFor: 74, goalsAgainst: 61, goalDifference: 13 },
        { position: 6,  team: { id: 61, name: "Chelsea FC",                     shortName: "Chelsea",        crest: "https://crests.football-data.org/61.png"   }, playedGames: 38, won: 18, draw: 9,  lost: 11, points: 63, goalsFor: 77, goalsAgainst: 63, goalDifference: 14 },
        { position: 7,  team: { id: 67,  name: "Newcastle United FC",           shortName: "Newcastle",      crest: "https://crests.football-data.org/67.png"   }, playedGames: 38, won: 18, draw: 6,  lost: 14, points: 60, goalsFor: 85, goalsAgainst: 62, goalDifference: 23 },
        { position: 8,  team: { id: 74, name: "Manchester United FC",           shortName: "Man United",     crest: "https://crests.football-data.org/66.png"   }, playedGames: 38, won: 14, draw: 4,  lost: 20, points: 46, goalsFor: 57, goalsAgainst: 58, goalDifference: -1 },
        { position: 9,  team: { id: 397, name: "Brighton & Hove Albion FC",     shortName: "Brighton",       crest: "https://crests.football-data.org/397.png"  }, playedGames: 38, won: 12, draw: 9,  lost: 17, points: 45, goalsFor: 55, goalsAgainst: 62, goalDifference: -7 },
        { position: 10, team: { id: 76, name: "Wolverhampton Wanderers FC",     shortName: "Wolves",         crest: "https://crests.football-data.org/76.png"   }, playedGames: 38, won: 13, draw: 6,  lost: 19, points: 45, goalsFor: 50, goalsAgainst: 74, goalDifference: -24 },
        { position: 11, team: { id: 563, name: "West Ham United FC",            shortName: "West Ham",       crest: "https://crests.football-data.org/563.png"  }, playedGames: 38, won: 14, draw: 3,  lost: 21, points: 45, goalsFor: 60, goalsAgainst: 74, goalDifference: -14 },
        { position: 12, team: { id: 1044, name: "AFC Bournemouth",              shortName: "Bournemouth",    crest: "https://crests.football-data.org/1044.png" }, playedGames: 38, won: 13, draw: 6,  lost: 19, points: 45, goalsFor: 54, goalsAgainst: 70, goalDifference: -16 },
        { position: 13, team: { id: 63,  name: "Fulham FC",                     shortName: "Fulham",         crest: "https://crests.football-data.org/63.png"   }, playedGames: 38, won: 13, draw: 5,  lost: 20, points: 44, goalsFor: 55, goalsAgainst: 61, goalDifference: -6 },
        { position: 14, team: { id: 354, name: "Crystal Palace FC",             shortName: "Crystal Palace", crest: "https://crests.football-data.org/354.png"  }, playedGames: 38, won: 13, draw: 5,  lost: 20, points: 44, goalsFor: 57, goalsAgainst: 58, goalDifference: -1 },
        { position: 15, team: { id: 402, name: "Brentford FC",                  shortName: "Brentford",      crest: "https://crests.football-data.org/402.png"  }, playedGames: 38, won: 10, draw: 9,  lost: 19, points: 39, goalsFor: 56, goalsAgainst: 65, goalDifference: -9 },
        { position: 16, team: { id: 62,  name: "Everton FC",                    shortName: "Everton",        crest: "https://crests.football-data.org/62.png"   }, playedGames: 38, won: 13, draw: 9,  lost: 16, points: 36, goalsFor: 40, goalsAgainst: 51, goalDifference: -11 },
        { position: 17, team: { id: 351, name: "Nottingham Forest FC",          shortName: "Nottm Forest",   crest: "https://crests.football-data.org/351.png"  }, playedGames: 38, won: 9,  draw: 9,  lost: 20, points: 32, goalsFor: 49, goalsAgainst: 67, goalDifference: -18 },
        { position: 18, team: { id: 1031, name: "Luton Town FC",                shortName: "Luton",          crest: "https://crests.football-data.org/1031.png" }, playedGames: 38, won: 6,  draw: 8,  lost: 24, points: 26, goalsFor: 52, goalsAgainst: 85, goalDifference: -33 },
        { position: 19, team: { id: 328, name: "Burnley FC",                    shortName: "Burnley",        crest: "https://crests.football-data.org/328.png"  }, playedGames: 38, won: 5,  draw: 9,  lost: 24, points: 24, goalsFor: 41, goalsAgainst: 78, goalDifference: -37 },
        { position: 20, team: { id: 356, name: "Sheffield United FC",           shortName: "Sheffield Utd",  crest: "https://crests.football-data.org/356.png"  }, playedGames: 38, won: 3,  draw: 7,  lost: 28, points: 16, goalsFor: 35, goalsAgainst: 104, goalDifference: -69 },
      ]
    }
  ]
};

// 2022/23 final standings → used as initial positions for 2023/24
// (Relegated: Leicester→Luton, Leeds→Burnley, Southampton→Sheffield Utd)
export const initialStandings2023 = [
  { position: 1,  name: "Manchester City FC",           shortName: "Man City",       crest: "https://crests.football-data.org/65.png"   },
  { position: 2,  name: "Arsenal FC",                   shortName: "Arsenal",        crest: "https://crests.football-data.org/57.png"   },
  { position: 3,  name: "Manchester United FC",         shortName: "Man United",     crest: "https://crests.football-data.org/66.png"   },
  { position: 4,  name: "Newcastle United FC",          shortName: "Newcastle",      crest: "https://crests.football-data.org/67.png"   },
  { position: 5,  name: "Liverpool FC",                 shortName: "Liverpool",      crest: "https://crests.football-data.org/64.png"   },
  { position: 6,  name: "Brighton & Hove Albion FC",    shortName: "Brighton",       crest: "https://crests.football-data.org/397.png"  },
  { position: 7,  name: "Aston Villa FC",               shortName: "Aston Villa",    crest: "https://crests.football-data.org/58.png"   },
  { position: 8,  name: "Tottenham Hotspur FC",         shortName: "Tottenham",      crest: "https://crests.football-data.org/73.png"   },
  { position: 9,  name: "Brentford FC",                 shortName: "Brentford",      crest: "https://crests.football-data.org/402.png"  },
  { position: 10, name: "Fulham FC",                    shortName: "Fulham",         crest: "https://crests.football-data.org/63.png"   },
  { position: 11, name: "Crystal Palace FC",            shortName: "Crystal Palace", crest: "https://crests.football-data.org/354.png"  },
  { position: 12, name: "Chelsea FC",                   shortName: "Chelsea",        crest: "https://crests.football-data.org/61.png"   },
  { position: 13, name: "Wolverhampton Wanderers FC",   shortName: "Wolves",         crest: "https://crests.football-data.org/76.png"   },
  { position: 14, name: "West Ham United FC",           shortName: "West Ham",       crest: "https://crests.football-data.org/563.png"  },
  { position: 15, name: "AFC Bournemouth",              shortName: "Bournemouth",    crest: "https://crests.football-data.org/1044.png" },
  { position: 16, name: "Nottingham Forest FC",         shortName: "Nottm Forest",   crest: "https://crests.football-data.org/351.png"  },
  { position: 17, name: "Everton FC",                   shortName: "Everton",        crest: "https://crests.football-data.org/62.png"   },
  // Newly promoted teams start at 18/19/20
  { position: 18, name: "Burnley FC",                   shortName: "Burnley",        crest: "https://crests.football-data.org/328.png"  },
  { position: 19, name: "Luton Town FC",                shortName: "Luton",          crest: "https://crests.football-data.org/1031.png" },
  { position: 20, name: "Sheffield United FC",          shortName: "Sheffield Utd",  crest: "https://crests.football-data.org/356.png"  },
];
